---
- name: playbook Jenkins Configuration
  hosts: jenkinsmaster
  become: yes

  tasks:
    - name: Disable Security for Installation
      xml:
        path: /var/lib/jenkins/config.xml
        xpath: /hudson/useSecurity
        value: 'false'

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    # Pause for 30 Seconds till jenkins is up and running
    - pause:
        seconds: 30

    - name: Download jenkins Cli 
      get_url:
        url: http://192.168.36.10:8080/jnlpJars/jenkins-cli.jar
        dest: /var/lib/jenkins/jenkins-cli.jar
    
    - name: Create User
      #shell: echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("user1", "password123")' | java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ groovy =
      shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("dummyuser", "dummypassword")' | java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 groovy =
      register: create_result

    - debug:
        var: create_result.output

    - name: Install Jenkinsplugin
      shell: java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }}
      loop:
        - script-security
        - junit
        - matrix-project
        - maven-plugin
        - credentials
        - ssh-credentials
        - javadoc
        - gitlab-plugin
        - gitlab-oauth
        - github-oauth
        - gitlab-logo
        - pipeline-multibranch-defaults
        - blueocean
        - build-pipeline-plugin
        - openshift-client
        - openshift-pipeline
        - pipeline-github
        - locale
        #recommended Plugins by Jenkins
        - cloudbees-folder
        - timestamper
        - build-pipeline-plugin
        - workflow-aggregator
        - github
        - pam-auth

        - antisamy-markup-formatter
        - ws-cleanup
        - github-branch-source
        - subversion
        - ldap

        - ant
        - build-timeout
        - pipeline-github-lib
        - ssh-slaves
        - email-ext

        - matrix-auth
        - pipeline-stage-view
        - gradle
        - credentials-binding
        - mailer

    - name: Enable Security for Installation
      xml:
        path: /var/lib/jenkins/config.xml
        xpath: /hudson/useSecurity
        value: 'true'

    - name: Enable Security for Installation
      xml:
        path: /var/lib/jenkins/config.xml
        xpath: /hudson/installStateName
        value: 'RUNNING'

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted