---
- name: playbook to setup jenkins
  hosts: jenkinsmaster
  become: yes

  tasks:
    - name: install git only if it is not already installed
      yum:
        name=git
        state=present
    
    - name: install java
      yum:
        name=java-1.8.0-openjdk.x86_64
        state=present

    - name: Install stable RH Jenkins Repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo 
        dest: /etc/yum.repos.d/jenkins.repo

    - rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: install Jenkins
      yum:
        name=jenkins
        state=present

    - name: Disable Security for Installation
      xml:
        path: /var/lib/jenkins/config.xml
        xpath: /hudson/useSecurity
        value: 'false'

    - name: Start Jenkins
      service:
        name: jenkins
        state: restarted