---

- name: Modify ExecStart in docker.service
  lineinfile:
    dest: /lib/systemd/system/docker.service
    state: present
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/dockerd-current -H unix:///var/run/docker.sock -H tcp://192.168.36.13:4243 -H tcp://127.0.0.1:4243 \\"

- name: reload systemd
  command: systemctl daemon-reload

- name: Restart Docker
  service:
    name: docker
    state: restarted