- name: ensure ssh password authentication is ok
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    line: "DOCKER_OPTS='-H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock'"

- name: modify ExecStart in docker.service
  lineinfile:
    dest: /lib/systemd/system/docker.service
    state: present
    regexp: "^ExecStart"
    line: "ExecStart=/usr/bin/docker -d -H fd:// $DOCKER_OPTS"
    backrefs: yes

- name: add Environmentfile in docker.service
  lineinfile:
    dest: /lib/systemd/system/docker.service
    line: "EnvironmentFile=/etc/default/docker"
    insertbefore: "^ExecStart"
  notify: restart-docker-service