---

- name: Disable Security for Installation
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/useSecurity
    value: 'false'

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 20
    state: started

- name: Create User
  shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("{{ jenkins.username }}", "{{ jenkins.password }}")' | java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins.hostname }}:8080 groovy =
  register: create_result

- debug:
    var: create_result

- name: Copy URL Configuration file
  copy:
    src: jenkins.model.JenkinsLocationConfiguration.xml
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
    owner: jenkins
    group: jenkins
    mode: "u=rw,g=r,o=r"

- name: Create root URL for Jenkins
  xml:
    path: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
    xpath: /jenkins.model.JenkinsLocationConfiguration/jenkinsUrl
    value: 'http://{{ jenkins.hostname }}:8080/'

- name: change authorization strategy class
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/authorizationStrategy
    attribute: class
    value: hudson.security.FullControlOnceLoggedInAuthorizationStrategy

- name: add child to authorization strategy
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/authorizationStrategy
    add_children:
    - denyAnonymousReadAccess: 'false'

- name: change security realm class
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/securityRealm
    attribute: class
    value: hudson.security.HudsonPrivateSecurityRealm

- name: add children to security realm
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/securityRealm
    add_children:
    - disableSignup: 'false'
    - enableCaptcha: 'false'

- name: Change install state name
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/installStateName
    value: 'RUNNING'

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 20
    state: started