---

- name: disable Security for Installation
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/useSecurity
    value: 'false'
- name: Restart Jenkins
  service:
    name: jenkins 
    state: restarted

- name: wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 20
    state: started

- name: create User
  shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("{{ jenkinscredentials.username }}", "{{ jenkinscredentials.password }}")' | java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins.hostname }}:8080 groovy =
  register: create_result

- debug:
    var: create_result

- name: copy URL Configuration File
  copy:
    src: jenkins.model.JenkinsLocationConfiguration.xml
    dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
    owner: jenkins
    group: jenkins
    mode: "u=rw,g=r,o=r"

- name: create root URL for Jenkins
  xml:
    path: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
    xpath: /jenkins.model.JenkinsLocationConfiguration/jenkinsUrl
    value: 'http://{{ jenkins.hostname }}:8080/'

- name: change Authorization Strategy Class
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/authorizationStrategy
    attribute: class
    value: hudson.security.FullControlOnceLoggedInAuthorizationStrategy

- name: add Child to Authorization Strategy
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/authorizationStrategy
    add_children:
    - denyAnonymousReadAccess: 'false'

- name: change Security Realm Class
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/securityRealm
    attribute: class
    value: hudson.security.HudsonPrivateSecurityRealm

- name: add Children to Security Realm
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/securityRealm
    add_children:
    - disableSignup: 'false'
    - enableCaptcha: 'false'

- name: change Install State of Jenkins
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/installStateName
    value: 'RUNNING'

- name: disable executors on Master
  xml:
    path: /var/lib/jenkins/config.xml
    xpath: /hudson/numExecutors
    value: '0'

- name: restart Jenkins
  service:
    name: jenkins 
    state: restarted

- name: wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 20
    state: started