---

- name: install Jenkinsplugins
  shell: java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins.hostname }}:8080/ -auth {{ jenkinscredentials.username }}:{{ jenkinscredentials.password }} install-plugin {{ item }}
  loop: "{{ jenkins.plugins }}"

- name: restart Jenkins
  service:
    name: jenkins 
    state: restarted

- name: wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 30
    state: started

- name: copy locale.xml to Jenkinsmaster
  copy:
    src: locale.xml
    dest: /var/lib/jenkins/locale.xml
    owner: jenkins
    group: jenkins
    mode: "u=rw,g=r,o=r"

- name: get locale-plugin version
  shell: java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins.hostname }}:8080 -auth {{ jenkinscredentials.username }}:{{ jenkinscredentials.password }} list-plugins locale | awk '{ print $4 }'
  register: localeversion

- name: set Locale Plugin Version
  xml:
    path: /var/lib/jenkins/locale.xml
    xpath: /locale
    attribute: plugin
    value: locale@"{{ localeversion.stdout }}"

- name: get id_rsa Key without Newline
  set_fact: ssh_key="{{ lookup('file', 'ssh-keys/id_rsa') | replace('\n', '') }}"
  register: ssh_key_no_newline

- name: get Crumb for Jenkins API
  uri:
    url: 'http://{{ jenkins.hostname }}:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    return_content: yes
  register: crumb

- name: insert GitHub Credential
  uri:
    method: POST
    url: 'http://{{ jenkins.hostname }}:8080/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ github.id }}",
          "secret": "{{ github.secret }}",
          "description": "Token provided for github",
          "$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
        }
      }

- name: copy GitHub Config XML
  copy:
    src: github-plugin-configuration.xml
    dest: /var/lib/jenkins/github-plugin-configuration.xml
    owner: jenkins
    group: jenkins
    mode: "u=rw,g=r,o=r"

- name: get GitHub Plugin Version
  shell: java -jar /var/lib/jenkins/jenkins-cli.jar -s http://{{ jenkins.hostname }}:8080 list-plugins github | awk '{ print $4 }'
  register: githubversion

- name: set GitHub Plugin Version
  xml:
    path: /var/lib/jenkins/github-plugin-configuration.xml
    xpath: /github-plugin-configuration
    attribute: plugin
    value: github@"{{ githubversion.stdout }}"
    
- name: set GitHub Plugin Credential Id
  xml:
    path: /var/lib/jenkins/github-plugin-configuration.xml
    xpath: /github-plugin-configuration/configs/github-server-config/credentialsId
    value: "{{ github.id }}"

- name: set GitHub Plugin URL
  xml:
    path: /var/lib/jenkins/github-plugin-configuration.xml
    xpath: /github-plugin-configuration/configs/github-server-config/name
    value: "{{ github.url }}"

- name: insert GitLab Credential
  uri:
    method: POST
    url: 'http://{{ jenkins.hostname }}:8080/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ gitlab.id }}",
          "secret": "{{ gitlab.secret }}",
          "description": "Token provided for gitlab",
          "$class": "org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl"
        }
      }

- name: insert GitLab User Credential
  uri:
    method: POST
    url: 'http://{{ jenkins.hostname }}:8080/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ gitlabUserAccount.id }}",
          "username": "{{ gitlabUserAccount.username }}",
          "password": "{{ gitlabUserAccount.password }}",
          "description": "User Account for gitlab",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }

- name: insert GitHub User Credential
  uri:
    method: POST
    url: 'http://{{ jenkins.hostname }}:8080/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ githubUserAccount.id }}",
          "username": "{{ githubUserAccount.username }}",
          "password": "{{ githubUserAccount.password }}",
          "description": "User Account for github",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }

- name: insert Jenkins .ssh Credential
  uri:
    method: POST
    url: 'http://{{ jenkins.hostname }}:8080/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkinscredentials.username }}"
    password: "{{ jenkinscredentials.password }}"
    force_basic_auth: yes
    status_code: 200,302
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "sshkey-jenkins",
          "username": "jenkins",
          "password": "",
          "privateKeySource": {
            "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource",
            "privateKey": "{{ ssh_key_no_newline }}"
          },
          "description": "apicredentials",
          "stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
        }
      }

- name: set GitLab Connection Name
  xml:
    path: /var/lib/jenkins/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/name
    value: "GitLab Connection Name"

- name: set GitLab Plugin URL
  xml:
    path: /var/lib/jenkins/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/url
    value: "{{ gitlab.url }}"

- name: set GitLab Plugin API Token
  xml:
    path: /var/lib/jenkins/com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig.xml
    xpath: /com.dabsquared.gitlabjenkins.connection.GitLabConnectionConfig/connections/com.dabsquared.gitlabjenkins.connection.GitLabConnection/apiTokenId
    value: "{{ gitlab.id }}"

- name: restart Jenkins
  service:
    name: jenkins 
    state: restarted

- name: wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 30
    state: started