---

- name: Install stable RH Jenkins Repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo 
    dest: /etc/yum.repos.d/jenkins.repo

- name: check jenkins rpm key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: install Jenkins
  yum:
    name=jenkins
    state=present
  notify: restart-jenkins-service

- name: Wait for Jenkinsmaster to get back online
  wait_for:
    host: localhost
    port: 8080
    delay: 20
    state: started

- name: Download jenkins Cli 
  get_url:
    url: http://{{ jenkins.hostname }}:8080/jnlpJars/jenkins-cli.jar
    dest: /var/lib/jenkins/jenkins-cli.jar